#!/bin/sh

echo PLAYLIST_FETCH_METHOD=$PLAYLIST_FETCH_METHOD > .env.local
echo PLAYLIST_FETCH_URL=$PLAYLIST_FETCH_URL >> .env.local
echo PLAYLIST_FETCH_AUTH_HEADER_KEY=$PLAYLIST_FETCH_AUTH_HEADER_KEY >> .env.local
echo PLAYLIST_FETCH_AUTH_HEADER_VALUE=$PLAYLIST_FETCH_AUTH_HEADER_VALUE >> .env.local
echo SEGMENTS_HOST=$SEGMENTS_HOST >> .env.local
echo MANIFEST_DURATION_IN_SECS=$MANIFEST_DURATION_IN_SECS >> .env.local
echo THUMBNAIL_VOD_PREFIX=$THUMBNAIL_VOD_PREFIX >> .env.local
echo THUMBNAIL_VOD_MANIFEST_HOST=$THUMBNAIL_VOD_MANIFEST_HOST >> .env.local
echo THUMBNAIL_VOD_MASTER_MANIFEST=$THUMBNAIL_VOD_MASTER_MANIFEST >> .env.local
echo THUMBNAIL_S3_BUCKET=$THUMBNAIL_S3_BUCKET >> .env.local
echo THUMBNAIL_S3_REGION=$THUMBNAIL_S3_REGION >> .env.local
echo THUMBNAIL_S3_ACCESS_KEY=$THUMBNAIL_S3_ACCESS_KEY >> .env.local
echo THUMBNAIL_S3_SECRET_KEY=$THUMBNAIL_S3_SECRET_KEY >> .env.local
echo THUMBOR_HOST=$THUMBOR_HOST >> .env.local
echo THUMBNAIL_HOST=$THUMBNAIL_HOST >> .env.local
echo RESET_SEQ_S3_BUCKET=$RESET_SEQ_S3_BUCKET >> .env.local
echo RESET_SEQ_S3_REGION=$RESET_SEQ_S3_REGION >> .env.local
echo RESET_SEQ_S3_ACCESS_KEY=$RESET_SEQ_S3_ACCESS_KEY >> .env.local
echo RESET_SEQ_S3_SECRET_KEY=$RESET_SEQ_S3_SECRET_KEY >> .env.local
echo RESET_SEQ_CF_DISTRIBUTION=$RESET_SEQ_CF_DISTRIBUTION >> .env.local
echo RESET_SEQ_NOTIFICATION_WEBHOOK=$RESET_SEQ_NOTIFICATION_WEBHOOK >> .env.local
echo DVR_HOST=$DVR_HOST >> .env.local

npm run build
npm run start
