#!/bin/sh

echo PLAYLIST_FETCH_METHOD=$PLAYLIST_FETCH_METHOD > .env.local
echo PLAYLIST_FETCH_URL=$PLAYLIST_FETCH_URL >> .env.local
echo PLAYLIST_FETCH_AUTH_HEADER_KEY=$PLAYLIST_FETCH_AUTH_HEADER_KEY >> .env.local
echo PLAYLIST_FETCH_AUTH_HEADER_VALUE=$PLAYLIST_FETCH_AUTH_HEADER_VALUE >> .env.local

npm run build
npm run start
