name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Docker Build Fast
      run: docker build fast --file Dockerfile --tag ntrphanikumar/manifest-stitcher:1.0.0 --tag ntrphanikumar/manifest-stitcher:1.0.0.$(date '+%Y%m%d')
    - name: Docker Push Fast
      run: docker push ntrphanikumar/manifest-stitcher --all-tags
