name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      # env:
      #   DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      #   DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      # run: |
      #   docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Docker Build
      run: docker build . --file Dockerfile --tag ntrphanikumar/manifest-stitcher:1.0.0 --tag ntrphanikumar/manifest-stitcher:1.0.0.$(date +%s)
    - name: Docker Push
      run: docker push ntrphanikumar/manifest-stitcher --all-tags
